extends SceneTree
const Adapter := preload("res://native_state.gd")
var checks := 0
var failures: Array[String] = []
func check(value: bool, label: String) -> void:
	checks += 1
	if not value: failures.append(label); push_error(label)
func _initialize() -> void: call_deferred("run")
func run() -> void:
	var a := Adapter.new()
	if "--restart" in OS.get_cmdline_user_args():
		a.load_checkpoint("user://blue-held.json")
		check(a.view().pending and a.view().delay_paused and is_equal_approx(a.view().delay_seconds,1.4),"fresh process retains exact paused delay")
		check(a.view().energy==1 and a.view().cargo==10 and a.view().trips==2,"fresh process paid ownership")
		check(not a.view().release_visible,"historical counters do not replay release")
		var held:=a.sim.contraption_save();a.tick(30)
		check(a.sim.contraption_save()==held,"explicit saved pause adds no time")
		check(a.act("resume").ok,"resume saved pending")
		a.signal_clear=false;held=a.sim.contraption_save();a.tick(30)
		check(a.sim.contraption_save()==held,"obstructed output holds restarted delay")
		a.signal_clear=true;a.tick(1.59)
		check(a.view().pending and a.view().energy==1,"no early payment before complete delay")
		a.tick(.02)
		check(not a.view().pending and a.view().moving and a.view().energy==0 and a.view().release_visible,"release once after remaining time")
		a.tick(10);check(a.view().at_landing and a.view().cargo==10 and a.view().trips==3,"same ten wood arrives once")
		var wood:int=a.view().wood_owned
		check(a.act("cargo").moved==10 and a.view().wood_owned==wood+10 and a.view().cargo==0,"fresh collection exact")
		check(not a.act("cargo").ok,"fresh repeated collection refuses")
		a.load_checkpoint("user://blue-claim.json")
		check(a.view().raw_claim==16 and a.view().mineral_owned==14,"fresh source claim retained")
		check(a.act("collect").moved==16 and a.view().mineral_owned==30,"fresh source collection once")
		check(not a.act("collect").ok,"fresh source cannot duplicate")
		a.load_checkpoint("user://blue-rare.json")
		check(a.view().rare_claim==1 and a.view().raw_claim==0 and not a.view().source_ready,"fresh rare-only claim remains visible in native view")
		check(a.act("rare").moved==1 and not a.act("rare").ok,"fresh rare transfers exactly once")
		finish();return
	check(a.view().pending and is_equal_approx(a.view().delay_seconds,.8),"paid saved request starts at exact 0.8 seconds")
	check(a.view().energy==1 and a.view().cargo==10 and a.view().trips==2 and not a.view().moving,"paid winding and cargo retained")
	check(a.view().pulses==2 and not a.view().release_visible,"saved accepted count is not a release")
	var original:=a.sim.contraption_save()
	check(not a.act("request").ok and a.sim.contraption_save()==original,"duplicate request cannot reset or queue")
	a.paused=true;a.tick(30)
	check(a.sim.contraption_save()==original and a.ambient_clock==0,"review pause freezes native and cosmetic clocks")
	check(not a.act("request").ok,"paused input refused")
	a.paused=false;a.active=false;a.tick(30)
	check(a.sim.contraption_save()==original and a.ambient_clock==0,"inactive radius adds no time")
	a.active=true;a.signal_clear=false;a.tick(30)
	check(a.sim.contraption_save()==original and not a.view().release_visible,"blocked output keeps exact request")
	a.signal_clear=true;a.tick(.6)
	check(is_equal_approx(a.view().delay_seconds,1.4) and a.view().energy==1,"active time advances only held delay")
	check(a.act("pause").ok,"explicit pause")
	a.checkpoint("user://blue-held.json");original=a.sim.contraption_save();a.tick(30)
	check(a.sim.contraption_save()==original,"explicit pause retains all machine fields")
	check(a.act("resume").ok,"explicit resume")
	a.tick(1.61)
	check(a.view().moving and a.view().energy==0 and not a.view().pending and a.view().release_visible,"native expiry pays one winding")
	check(a.view().progress==0,"new departure not credited the whole expiry frame")
	a.paused=true;var age:float=a.release_age;a.tick(20)
	check(a.release_age==age,"review pause freezes transient release")
	a.paused=false;a.cargo_clear=false;original=a.sim.contraption_save();a.tick(20)
	check(a.sim.contraption_save()==original and not a.view().release_visible,"physical cargo obstruction retains paid trip while transient ends")
	check(a.act("disconnect").ok,"disconnect after departure")
	a.cargo_clear=true;a.tick(10)
	check(a.view().at_landing and a.view().cargo==10 and a.view().trips==3,"disconnect preserves departed paid trip")
	var wood:int=a.view().wood_owned
	check(a.act("cargo").moved==10 and a.view().wood_owned==wood+10,"exact cargo transfer")
	check(not a.act("cargo").ok,"no duplicate cargo")
	check(a.act("connect").ok and a.act("request").ok,"unwound receiver can receive a held request")
	a.tick(3.01)
	check(not a.view().pending and not a.view().moving and a.view().energy==0 and a.view().release_visible,"unwound release consumes request without motion")
	check(a.act("wind").ok,"new manual winding")
	a.tick(10);check(not a.view().moving and a.view().energy==1,"later winding never replays failed release")
	a.input_clear=false;original=a.sim.contraption_save()
	check(not a.act("request").ok and a.sim.contraption_save()==original,"blocked input adds no request")
	a.input_clear=true;check(a.act("request").ok,"new paid return request")
	a.tick(1);check(a.act("cancel").ok,"cancel pending")
	a.tick(10);check(not a.view().pending and not a.view().moving and a.view().energy==1 and not a.view().release_visible,"cancel neither releases nor spends")
	check(a.act("request").ok,"request for rewire proof")
	check(a.act("disconnect").ok and not a.view().pending,"downstream disconnect cancels pending")
	check(a.act("connect").ok,"reconnect")
	a.tick(10);check(not a.view().moving and a.view().energy==1,"reconnect cannot restore cancelled request")
	check(a.act("request").ok,"new request for upstream cancellation")
	check(a.sim.contraption_link(a.WHITE,"",true).ok and not a.view().pending,"upstream rewire cancels pending")
	check(a.sim.contraption_link(a.WHITE,a.BLUE,true).ok,"restore upstream route")
	check(a.act("request").ok,"new cargo-blocked request")
	a.cargo_clear=false;a.tick(3.01)
	check(not a.view().pending and not a.view().moving and a.view().energy==1 and a.view().release_visible,"blocked cargo consumes request without spending drive")
	a.cargo_clear=true;a.tick(10)
	check(not a.view().moving and a.view().energy==1,"clearing cargo cannot replay refusal")
	check(a.act("request").ok,"new return request after clearing")
	a.tick(3.01);a.tick(10)
	check(not a.view().at_landing and a.view().trips==4 and a.view().energy==0,"new paid empty return arrives")
	# Published fixed Blue lots, partial collections and reformation.
	a.load_checkpoint("res://paid-checkpoint.json")
	check(a.view().mineral_owned==14 and a.view().lot==1,"actual published harvested Blue and paid kit")
	var ledger:=a.sim.leyline_save();a.source_blocked=true
	check(not a.act("work").ok and a.sim.leyline_save()==ledger,"workspace refusal preserves source")
	a.source_blocked=false
	for i in 4:check(a.act("work").ok,"paid-save source extraction stage")
	check(a.view().raw_claim==16 and a.view().mineral_owned==14,"source owns released flakes")
	a.checkpoint("user://blue-claim.json")
	ledger=a.sim.leyline_save()
	check(not a.act("work").ok and a.sim.leyline_save()==ledger,"claim prevents further work")
	check(a.act("collect").moved==16 and a.view().mineral_owned==30,"collect one lot")
	check(not a.act("collect").ok,"no repeated flakes")
	for lot in 6:
		for step in 4:check(a.act("work").ok,"exhaust actual source")
		check(a.act("collect").moved==16,"collect actual remaining lot")
	check(not a.view().source_ready and a.view().mineral_owned==126,"spent native state")
	a.source_blocked=true;a.tick(700)
	check(not a.view().source_ready and a.view().formation==600,"blocked renewal caps at declared time")
	a.source_blocked=false;a.tick(.01)
	check(a.view().source_ready and a.view().lot==0,"clear native renewal")
	for i in 4:a.act("work")
	check(a.act("collect").moved==2 and a.view().raw_claim==14 and a.view().mineral_owned==128,"partial collection retains source ownership")
	ledger=a.sim.leyline_save()
	check(not a.act("collect").ok and a.sim.leyline_save()==ledger,"full family cannot lose flakes")
	# Separate accelerated rare-outcome coverage. Consume test-carried flakes to
	# clear capacity, but never grant inventory or edit native hidden outcomes.
	a.load_checkpoint("res://paid-checkpoint.json")
	var found := false
	for lot in 160:
		var carried: int=a.view().mineral_owned
		if carried>0:a.sim.consume_material("blue_flake",carried)
		if a.view().lot==a.view().lots:a.tick(600)
		for step in 4:a.act("work")
		if a.view().rare_claim>0:
			found=true
			check(a.view().raw_claim==16,"actual fixed outcome releases rare beside raw")
			check(a.act("collect").moved==16 and a.view().rare_claim==1 and not a.view().source_ready,"raw collection cannot consume or hide rare claim")
			a.checkpoint("user://blue-rare.json");ledger=a.sim.leyline_save()
			a.load_checkpoint("user://blue-rare.json")
			check(a.sim.leyline_save()==ledger,"rare-only reload exact")
			check(a.act("rare").moved==1 and not a.act("rare").ok,"rare collection exact once")
			break
		a.act("collect")
	check(found,"native fixed stream contains rare within bounded test")
	finish()
func finish() -> void:
	var result:={"checks":checks,"failures":failures,"restart":"--restart" in OS.get_cmdline_user_args()}
	var path:="res://evidence/native-restart.json" if result.restart else "res://evidence/native-checks.json"
	FileAccess.open(path,FileAccess.WRITE).store_string(JSON.stringify(result,"\t"))
	print("BLUE_NATIVE_CHECKS ",checks," failures ",failures.size())
	quit(0 if failures.is_empty() else 1)
