extends "res://tests/rf06b/placement.gd"
func _ready() -> void:
 output=OS.get_environment("WROUGHTWILD_RF06B_OUTPUT")
 set_physics_process(false)
 seed_controls=SEED_CONTROLS.new()
 add_child(seed_controls)
 seed_controls.configure(self,"904",output.path_join("checked-world.json"))
 restore_fen.call_deferred()
func restore_fen() -> void:
 var saved: Dictionary=JSON.parse_string(FileAccess.get_file_as_string(output.path_join("checked-world.json")))
 var expected: Dictionary=JSON.parse_string(FileAccess.get_file_as_string(output.path_join("expected.json")))
 if not check(seed_controls.continue_saved(),"fresh-process ordinary Continue"):return finish_rf("continue")
 quiet()
 setup_lake()
 fen_point=Vector3(expected.fen[0],expected.fen[1],expected.fen[2])
 set_origins()
 await tick()
 quiet()
 var restored: Dictionary=JSON.parse_string(JSON.stringify(SaveManager.new().capture(player),"",true,true))
 check(world_seed==77 and world_profile=="frontier_v8","saved seed/profile override new seed input")
 check(_sim().export_json()==saved.sim,"exact native progression and possessions")
 for key in ["blocks","stations","contraptions","leylines","resource_nodes","world_drops","broken_blocks"]:
  check(restored.get(key,[])==saved.get(key,[]),"exact restored "+key)
 check(hash(terrain.map.heights)==int(expected.height_digest) and hash(terrain.map.lakes)==int(expected.water_digest),"native terrain and lake unchanged")
 check(hash(snapshot())==int(expected.cover_digest) and hidden_count()==int(expected.hidden),"Continue repeats cover and paid clearing exactly")
 ready_at(Vector3(home.x+.5,home.y+1.1,home.z+.5)-axis*4)
 terrain.set_process(true)
 for i in 20:await tick()
 check(player.is_on_floor() and not player.swimming,"restored dry home remains supported")
 var before:=player.position
 player.test_walk=Vector2(1,0)
 for i in 18:await tick()
 player.test_walk=Vector2.ZERO
 check(player.position.distance_to(before)>.3,"ordinary controller moves after Continue")
 var p:=Vector3(lake.x,float(lake.surface_y)-.2,lake.z)
 terrain.ensure_area(p,16)
 check(not LakeWater.contact(terrain,p).is_empty(),"original lake contact remains available")
 check(SaveManager.new().write(output.path_join("resaved-world.json"),player),"ordinary resave succeeds")
 finish_rf("continue")
