"""Write the beetle descriptor from a checked source report and runtime files."""
from pathlib import Path
import json,hashlib,sys
src,root=map(Path,sys.argv[1:])
r=json.loads((src/'rig-report.json').read_text());cfg=r['settings']
asset={
 'enemy_id':'gloom_crawler','role':'swarm','source_stage':'Approved ART-06C v02 ground beetle, fitted MOB-04 '+src.name,
 'model':'res://assets/authored/roster/gloom_crawler/model.glb',
 'maps':{k:'res://assets/authored/roster/gloom_crawler/'+v for k,v in [('base','base.png'),('orm','orm.png'),('scar','scar-mask.png')]},
 'nodes_relative_to_model_root':{'skeleton':'BeetleRig/Skeleton3D','animation_player':'AnimationPlayer','mesh':'BeetleRig/Skeleton3D/BeetleSkin'},
 'geometry':{'source_triangles':r['source_triangles'],'triangles':r['runtime_triangles'],'blender_vertices':r['runtime_vertices'],'bones':len(r['bones']),'surfaces':1,'max_weights':r['max_weights'],'simplification':'Automatic triangle collapse after coincident-position welding; three duplicate faces removed by validation. No manual retopology or normal bake.'},
 'clips':{n:{'duration_seconds':round(s*cfg['source_fps'])/cfg['source_fps'],'authored_duration_seconds':s,'loop':n in ['idle','walk']} for n,s in r['clips_seconds'].items()},
 'fit':{'source_coordinates':'Blender Z-up, +Y forward; GLB Y-up, -Z forward. Unlike the ram, no yaw reversal.', 'uniform_metres_per_source_unit':cfg['uniform_metres_per_source_unit'],'ground_offset_metres':[0,0,0],'rotation_y_degrees':0,'extra_cull_margin_source_units':cfg['cull_margin_source_units'],'source_rest_bounds_blender':r['source_bounds'],'root_motion':False,'capsule_limit':'The low wide silhouette differs from the unchanged upright radius .35 / height 1.3 collider. Aspect ratio, targeting and contact reach are preserved.'},
 'material':{'core_colour_godot_Color':[.26,.54,.62],'damage_tint_linear':[.16,.14,.12],'period_seconds':4,'peak_emission':2.4,'minimum_light':.32,'crest_width':.2,'pulse_mode':3,'base_colour_space':'sRGB source_color','orm_colour_space':'linear data: G roughness, B metallic; source AO retained','scar_colour_space':'linear data: R core, G damage, B connected travel delay','albedo_formula':'mix(base, base * damage_tint, scar.g)','normal_map':None,'clock':'Pause-aware ambient clock, per-instance phase. Native status takes priority; scars never deal damage or heal.'},
 'integration':{'legacy_mesh_scale':1,'legacy_mesh_scale_purpose':'Native swarm has no humanoid reduction. Family and elite size already live on the parent mesh and apply once.', 'cosmetic_stride_metres':cfg['cosmetic_stride_metres'],'cosmetic_stride_purpose':cfg['purpose']['cosmetic_stride_metres'],'actual_source_travel_units_per_cycle':cfg['step_units']/cfg['stance_fraction'],'stance_fraction':cfg['stance_fraction'],'tripod_phases':{leg['name']:leg['phase'] for leg in cfg['legs']},'timing':'Normalized native windup; native attack_released(strike) starts existing CreatureMotion cosmetic release window. No damage events or movement tracks.','continue':'Existing transient_actor_presentations reset clears cosmetic release; no persistent fields.'},
 'provenance':{'editable_master':str(src/'gloom_crawler-rigged.blend'),'rig_report':str(src/'rig-report.json'),'immutable_input_receipt':'D:/Wroughtwild/source-art/mob04-beetle/input-art06c/source-selection.json','recipe':'tools/wroughtwild-mob04-beetle/build_beetle.py','tuning':'tools/wroughtwild-mob04-beetle/rig.json','files_sha256':{p.name:hashlib.sha256(p.read_bytes()).hexdigest() for p in root.iterdir() if p.suffix in ['.glb','.png']}},
 'known_limits':['Foot sliding from deliberate native cadence; no runtime terrain IK.','Generated fine cavities and weight transitions remain prototype quality.','One runtime detail level; full performance impact and owner playtesting deferred.','Physical era variants and significant underground lag remain separate work.']}
(root/'asset.json').write_text(json.dumps(asset,indent=2)+'\n')
