extends SceneTree
const Adapter:=preload("res://native_state.gd")
var checks:=0
var failures:Array[String]=[]
func check(value:bool,label:String)->void:
	checks+=1
	if not value:failures.append(label);push_error(label)
func _initialize()->void:call_deferred("run")
func run()->void:
	var a:=Adapter.new()
	if "--restart" in OS.get_cmdline_user_args():
		a.load_checkpoint("user://green-paid-work.json")
		check(a.view().moving and is_equal_approx(a.view().progress,3.75/14.0) and a.view().cargo==10,"fresh exact paid cargo progress")
		check(a.view().feeder_progress==1.25 and a.view().clay_escrow==8 and a.view().fuel_escrow==1 and a.view().drive_escrow==1,"fresh exact feeder escrow and progress")
		check(a.view().energy==0 and a.view().feeder_energy==0 and a.view().pulses==2 and not a.view().passage_visible,"fresh counter does not replay passage or invent energy")
		a.cargo_clear=false;a.feeder_clear=false;var held:=a.sim.contraption_save();a.tick(30)
		check(a.sim.contraption_save()==held,"fresh physical refusal retains both paid jobs")
		a.cargo_clear=true;a.feeder_clear=true;a.tick(10)
		check(a.view().at_landing and a.view().trips==5 and a.view().cargo==10,"fresh same cargo delivered once")
		check(a.view().bricks==8 and a.view().cycles==2 and not a.view().feeder_working,"fresh one paid firing adds four bricks")
		check(a.act("cargo").moved==10 and not a.act("cargo").ok,"fresh cargo transfer once")
		check(a.act("bricks").moved==8 and not a.act("bricks").ok,"fresh old plus new brick transfer once")
		a.load_checkpoint("user://green-rare.json")
		check(a.view().rare_claim==1 and a.view().raw_claim==0 and not a.view().source_ready,"fresh rare-only claim remains visible")
		check(a.act("rare").moved==1 and not a.act("rare").ok,"fresh rare transfers once")
		a.load_checkpoint("user://green-pending.json")
		check(a.view().blue_pending and a.view().blue_paused and a.view().blue_elapsed==1.1 and not a.view().passage_visible,"fresh pending Blue retains delay without Green replay")
		held=a.sim.contraption_save();a.tick(30);check(a.sim.contraption_save()==held,"saved upstream pause remains exact")
		a.act("resume");a.tick(1.91)
		check(a.view().first_started and a.view().second_started and a.view().pulses==2,"fresh remaining delay pays both owners once")
		finish();return
	check(a.view().blue_pending and a.view().blue_elapsed==.5 and a.view().pulses==1 and not a.view().passage_visible,"published pending delay and historical Green counter")
	check(a.view().cargo==10 and a.view().energy==1 and a.view().trips==4,"published ten wood and winding")
	check(a.view().feeder_energy==1 and a.view().clay_input==8 and a.view().fuel_input==3 and a.view().bricks==4 and a.view().cycles==1,"published feeder ingredients drive and old output")
	var held:=a.sim.contraption_save();a.paused=true;a.tick(20)
	check(a.sim.contraption_save()==held and a.ambient_clock==0,"review pause freezes all clocks")
	check(not a.act("request").ok,"paused input refuses")
	a.paused=false;a.active=false;a.tick(20)
	check(a.sim.contraption_save()==held and a.ambient_clock==0,"inactive radius adds no time")
	a.active=true;a.blue_output_clear=false;a.tick(20)
	check(a.sim.contraption_save()==held and not a.view().passage_visible,"blocked upstream has no Green passage")
	a.blue_output_clear=true;a.tick(.6);a.act("pause");a.checkpoint("user://green-pending.json")
	check(is_equal_approx(a.view().blue_elapsed,1.1) and a.view().blue_paused,"explicit pending checkpoint")
	a.act("resume");a.tick(1.91)
	check(a.view().pulses==2 and a.view().passage_visible and a.view().first_sent and a.view().second_sent,"one native Green event reaches both clear branches")
	check(a.view().first_started and a.view().second_started and a.view().energy==0 and a.view().feeder_energy==0,"each receiver pays own winding")
	check(a.view().clay_escrow==8 and a.view().fuel_escrow==1 and a.view().fuel_input==2 and a.view().bricks==4,"one real batch escrow no instant output")
	check(a.view().progress==0 and a.view().feeder_progress==0,"release frame cannot over-credit new jobs")
	a.tick(.35);a.paused=true;var age:float=a.passage_age;held=a.sim.contraption_save();a.tick(20)
	check(a.passage_age==age and a.sim.contraption_save()==held,"review pause freezes transient and both jobs")
	a.paused=false;a.tick(.9);a.checkpoint("user://green-paid-work.json")
	check(not a.view().passage_visible and a.view().feeder_progress==1.25,"passage ends independently of longer paid work")
	a.cargo_clear=false;a.feeder_clear=false;held=a.sim.contraption_save();a.tick(20)
	check(a.sim.contraption_save()==held,"both blocked jobs retain exact ownership")
	a.cargo_clear=true;a.feeder_clear=true;a.tick(10)
	check(a.view().cargo==10 and a.view().trips==5 and a.view().bricks==8 and a.view().cycles==2,"both jobs complete once")
	check(a.act("cargo").moved==10 and not a.act("cargo").ok,"native cargo collected once")
	check(a.act("bricks").moved==8 and not a.act("bricks").ok,"native old plus new output collected once")
	# Independent branch and receiver refusals from the same paid baseline.
	for which in ["first","second","both","cargo","feeder"]:
		a.load_checkpoint("res://paid-checkpoint.json")
		a.first_clear=which not in ["first","both"];a.second_clear=which not in ["second","both"]
		a.cargo_clear=which!="cargo";a.feeder_clear=which!="feeder";a.tick(2.51)
		var first_expected:bool=which not in ["first","both","cargo"]
		var second_expected:bool=which not in ["second","both","feeder"]
		check(a.view().passage_visible and a.view().pulses==2 and not a.view().blue_pending,"Green receives/consumes one request: "+which)
		check(a.view().first_sent==a.first_clear and a.view().second_sent==a.second_clear,"light marks signal clearance, separate from work: "+which)
		check(a.view().first_started==first_expected and a.view().energy==(0 if first_expected else 1),"first payment independent: "+which)
		check(a.view().second_started==second_expected and a.view().feeder_energy==(0 if second_expected else 1),"second payment independent: "+which)
		check(a.view().clay_input==(0 if second_expected else 8) and a.view().fuel_input==(2 if second_expected else 3),"refused second branch keeps ingredients: "+which)
		a.first_clear=true;a.second_clear=true;a.cargo_clear=true;a.feeder_clear=true;a.tick(20)
		check(a.view().trips==(5 if first_expected else 4) and a.view().bricks==(8 if second_expected else 4),"clearing refusal never queues later work: "+which)
	a.load_checkpoint("res://paid-checkpoint.json")
	held=a.sim.contraption_save()
	check(not a.act("request").ok and a.sim.contraption_save()==held,"duplicate pending request cannot duplicate Green")
	check(not a.sim.contraption_link_second(a.GREEN,a.DRUM,true).ok and a.sim.contraption_save()==held,"duplicate receiver rejected without pending-state mutation")
	check(not a.sim.contraption_link(a.GREEN,a.BLUE,true).ok and a.sim.contraption_save()==held,"cyclic/signal receiver refuses without mutation")
	check(a.act("disconnect_second").ok and not a.view().blue_pending,"rewire cancels upstream held request")
	check(a.act("connect_second").ok,"reconnect actual feeder")
	a.tick(20);check(a.view().energy==1 and a.view().feeder_energy==1 and not a.view().passage_visible,"reconnect does not restore cancelled work")
	check(a.act("request").ok and a.act("cancel").ok,"cancel new held request")
	a.tick(20);check(a.view().pulses==1 and a.view().energy==1 and a.view().feeder_energy==1,"cancel never creates Green event or payment")
	a.act("request");a.tick(3.01);a.tick(10)
	check(a.act("request").ok,"receivers can be asked again without winding")
	a.tick(3.01)
	check(a.view().passage_visible and a.view().first_sent and a.view().second_sent and not a.view().first_started and not a.view().second_started,"both unwound branches receive requests without free work")
	a.act("wind");a.act("wind_feeder");a.tick(20)
	check(not a.view().moving and not a.view().feeder_working and a.view().energy==1 and a.view().feeder_energy==1,"later winding cannot replay failed requests")
	# Actual remaining fixed source lots include one rare Preserving claim.
	a.load_checkpoint("res://paid-checkpoint.json")
	check(a.view().mineral_owned==14 and a.view().lot==1,"published Green stock and paid kit")
	var ledger:=a.sim.leyline_save();a.source_blocked=true
	check(not a.act("work").ok and a.sim.leyline_save()==ledger,"blocked source cannot spend stock")
	a.source_blocked=false;var rare_found:=false
	for lot in 7:
		for step in 4:check(a.act("work").ok,"real source extraction")
		check(a.view().raw_claim==16,"actual raw lot held by source")
		check(a.act("collect").moved==16,"collect real resin")
		if a.view().rare_claim>0:
			rare_found=true;check(not a.view().source_ready and a.view().raw_claim==0,"rare-only ownership remains visible")
			a.checkpoint("user://green-rare.json");ledger=a.sim.leyline_save();a.load_checkpoint("user://green-rare.json")
			check(a.sim.leyline_save()==ledger,"rare-only restore exact")
			check(a.act("rare").moved==1 and not a.act("rare").ok,"rare transfer once")
	check(rare_found and a.view().mineral_owned==126 and not a.view().source_ready,"fixed rare outcome and exhausted stock")
	a.source_blocked=true;a.tick(700)
	check(a.view().formation==600 and not a.view().source_ready,"blocked reformation caps")
	a.source_blocked=false;a.tick(.01)
	check(a.view().source_ready and a.view().lot==0,"unblocked native reformation")
	for step in 4:a.act("work")
	check(a.act("collect").moved==2 and a.view().raw_claim==14 and a.view().mineral_owned==128,"partial collection keeps fourteen source-owned resin")
	ledger=a.sim.leyline_save();check(not a.act("collect").ok and a.sim.leyline_save()==ledger,"full family refuses without loss")
	finish()
func finish()->void:
	var result:={"checks":checks,"failures":failures,"restart":"--restart" in OS.get_cmdline_user_args()}
	var path:="res://evidence/native-restart.json" if result.restart else "res://evidence/native-checks.json"
	FileAccess.open(path,FileAccess.WRITE).store_string(JSON.stringify(result,"\t"))
	print("GREEN_NATIVE_CHECKS ",checks," failures ",failures.size());quit(0 if failures.is_empty() else 1)
