extends "res://tests/land04/common.gd"
## First ordinary Blue composition capture. Arrival is staged; the scene is
## generated by normal New World and uses its real source/workplace/controller.
func _ready() -> void:
 begin()
 run.call_deferred()
func run() -> void:
 if not await started():return finish_job("early")
 var blue:=journey("blue")
 if not check(not blue.is_empty(),"Blue seeded journey is available"):return finish_job("early")
 await journey_picture(blue,"blue-early")
 var node:=source("blue_home_margin")
 if check(node!=null and node.supported(),"ordinary Blue source has native ground support"):
  await aim_source(node)
  check(not player.swimming,"Blue work stance is dry")
  await still("blue-work-early.png")
 finish_job("early",{"blue":blue,"player":player.position})