"""Create a local, matched gameplay comparison from both completed reviews."""
import json
from pathlib import Path

root = Path(__file__).resolve().parents[2] / 'build' / 'frontier-polish'
before = json.loads((root / 'before' / 'manifest.json').read_text(encoding='utf8'))
after = json.loads((root / 'after' / 'manifest.json').read_text(encoding='utf8'))
walk_file = root / 'walk' / 'manifest.json'
walk = json.loads(walk_file.read_text(encoding='utf8')) if walk_file.exists() else {}
interior = 'interior' if (root / 'interior' / 'lantern-workshop-day.png').exists() else 'walk'
for old, new in zip(before['views'], after['views'], strict=True):
    if old['id'] != new['id'] or old['camera_transform'] != new['camera_transform']:
        raise ValueError('Comparison cameras differ: ' + old['id'])
for stem in [r['id'] + '-' + hour for r in after['views'] for hour in ['day', 'dusk']] + ['find-' + k for k in ['lanternheart', 'thrumroot', 'stormglass', 'pullstone', 'ventlung']]:
    for version in ['before', 'after']:
        if not (root / version / (stem + '.png')).is_file():
            raise FileNotFoundError(version + '/' + stem)

page = '''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Wroughtwild · Frontier art comparison</title><style>
*{box-sizing:border-box}body{margin:0;background:#141b19;color:#ede8db;font:16px/1.55 system-ui,sans-serif}main{max-width:1504px;margin:auto;padding:28px 24px 64px}h1{font:500 clamp(28px,4vw,48px)/1.16 Georgia,serif;max-width:900px;margin:10px 0 18px}p{max-width:920px;color:#b9c4b8}.eyebrow{font-size:12px;text-transform:uppercase;letter-spacing:.12em;color:#bfca9c}.controls{display:flex;gap:9px;flex-wrap:wrap;align-items:center;margin:18px 0}button,select{background:#293a30;color:#eee8d9;border:1px solid #52664b;border-radius:5px;padding:10px 13px;font:inherit;cursor:pointer}button:hover,button.active{background:#57684a}.compare{position:relative;overflow:hidden;border:1px solid #4b5b45;border-radius:9px;aspect-ratio:1.6;background:#09100c}.compare img{position:absolute;inset:0;width:100%;height:100%;object-fit:contain}.compare .old{clip-path:inset(0 calc(100% - var(--split,50%)) 0 0)}.divider{position:absolute;left:var(--split,50%);height:100%;width:2px;background:#f2e9cc;pointer-events:none}.tag{position:absolute;bottom:14px;border-radius:4px;padding:5px 10px;background:#121b16e0;font-size:13px}.tag.before{left:14px}.tag.after{right:14px}.slider{width:min(680px,100%);accent-color:#b9cd99}.note{font-size:13px;color:#a7b8a5}h2{font:500 28px/1.25 Georgia,serif;margin:38px 0 14px}table{border-collapse:collapse;width:100%;font-size:14px}th,td{text-align:left;padding:12px;border-bottom:1px solid #384737}th{color:#c8d6b9;font-weight:500}.table-wrap{overflow:auto}a{color:#cad9b4}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(245px,1fr));gap:14px;margin:26px 0}.cards article{background:#202d25;padding:18px;border:1px solid #3d513d;border-radius:7px}.cards b{display:block;font-weight:500;font-size:19px}.cards p{font-size:14px;margin-bottom:0}@media(max-width:650px){main{padding:18px 12px}.controls button,.controls select{font-size:13px}td,th{padding:9px}}
</style><main><div class="eyebrow">Wroughtwild · 6 September 2026 · Actual gameplay captures</div><h1>From isolated landmarks to places with depth</h1><p>Heavier crowns and irregular roots, clustered shore growth and worn rock shelves give the three regions more shape at walking height. Drag the divider to inspect the same view before and after the art pass.</p>
<div class="controls"><label for="view">Place</label><select id="view"></select><button id="day" class="active">Daylight</button><button id="dusk">Matched dusk</button></div>
<div class="compare" id="comparison"><img id="newImage" alt="Updated gameplay view"><img class="old" id="oldImage" alt="Previous gameplay view"><div class="divider"></div><span class="tag before">Before</span><span class="tag after">After</span></div>
<div class="controls"><label for="split">Compare</label><input class="slider" id="split" aria-label="Amount of previous view shown" type="range" min="0" max="100" value="50"><button id="allBefore">Show before</button><button id="allAfter">Show after</button></div>
<p class="note">Seed 1 · 1440 × 900 · Forward+ · 75° field of view · identical camera transforms and fixed hour. Regional light settings are part of the change. Dusk uses the same reduced direct light in both versions. This is a visual review; the owner’s judgment of the finish remains open.</p>
<div class="cards"><article><b>Rootvault Wildwood</b><p>Irregular old boles sit among supporting trees, saplings, fern beds and deadfall. Crowns overlap without filling the walking routes.</p></article><article><b>Lantern Fen</b><p>Broken hollows and smaller bent trees rise from sedge patches. Variable shallow pools have planted margins and clear approaches.</p></article><article><b>Glasswind Uplands</b><p>Low weathered shelves, shared strata directions and lee-side scree replace the repeated upright spikes.</p></article></div>
<section id="walkSection"><h2>Along the walking routes</h2><p>These short walks follow the generated approaches at 1.65 m eye height and ordinary movement speed. The camera moves through the live world, with terrain and resources streaming normally.</p><div class="controls"><select id="walkRegion" aria-label="Walking route"></select><button id="playWalk">Play walk</button><input class="slider" id="walkFrame" aria-label="Walking frame" type="range" min="0" value="0"><span id="walkTime"></span></div><div class="compare"><img id="walkImage" alt="Walking through the updated region"></div><p class="note">Four captured images per second; this is a camera review, not a human playtest or full-rate gameplay recording. Timing was measured separately with no screenshot readback.</p><div class="cards"><article><b>Shallow Fen shoreline</b><img src="walk/shoreline.png" style="width:100%" alt="Reed margins around a supported shallow pool"></article><article><b>A material workshop</b><img src="walk/lantern-workshop-day.png" style="width:100%" alt="Resinheart workshop and lantern in daylight"></article><article><b>The same room at dusk</b><img src="walk/lantern-workshop-dusk.png" style="width:100%" alt="Warm local lantern inside the same workshop at dusk"></article></div></section>
<h2>Cost of the same views</h2><p class="note">600 uncapped frame samples after 90 warmup frames in each settled view, with terrain streaming completed first. Results are from this RTX 5090 machine and do not predict lower-end hardware. Startup includes initial terrain, resources and décor; sequential runs may have different cache state.</p>
<div class="table-wrap"><table><thead><tr><th>View</th><th>Median, before → after</th><th>p95, before → after</th><th>p95 change</th><th>Draw calls, before → after</th></tr></thead><tbody id="metrics"></tbody></table></div><p class="note" id="startup"></p><p class="note">Changes above 10% are investigated in the implementation report. These static captures do not measure movement or streaming hitches.</p>
<p><a href="before/manifest.json">Before measurements</a> · <a href="after/manifest.json">After measurements</a> · <a href="../../docs/prototype/frontier-art-refinement-2026-09-06.md">Implementation, checks and limitations</a></p>
</main><script>
const before=__BEFORE__,after=__AFTER__,walk=__WALK__;
const labels={rootvault_wildwood:'Rootvault Wildwood',lantern_fen:'Lantern Fen',glasswind_uplands:'Glasswind Uplands','find-lanternheart':'Lanternheart approach','find-thrumroot':'Thrumroot approach','find-stormglass':'Stormglass approach','find-pullstone':'Pullstone approach','find-ventlung':'Ventlung approach'};
const select=document.getElementById('view'),slider=document.getElementById('split');let hour='day';
for(const id of Object.keys(labels)){const o=document.createElement('option');o.value=id;o.textContent=labels[id];select.append(o)}
function show(){const isFind=select.value.startsWith('find-'),name=select.value+(isFind?'':'-'+hour);document.getElementById('oldImage').src='before/'+name+'.png';document.getElementById('newImage').src='after/'+name+'.png';for(const h of ['day','dusk']){const b=document.getElementById(h);b.disabled=isFind;b.classList.toggle('active',h===hour&&!isFind)}}
function split(){document.getElementById('comparison').style.setProperty('--split',slider.value+'%')}
select.onchange=show;slider.oninput=split;for(const h of ['day','dusk'])document.getElementById(h).onclick=()=>{hour=h;show()};document.getElementById('allBefore').onclick=()=>{slider.value=100;split()};document.getElementById('allAfter').onclick=()=>{slider.value=0;split()};show();
for(const row of after.views){const old=before.views.find(x=>x.id===row.id),tr=document.createElement('tr');for(const value of [labels[row.id],old.median_ms.toFixed(3)+' → '+row.median_ms.toFixed(3)+' ms',old.p95_ms.toFixed(3)+' → '+row.p95_ms.toFixed(3)+' ms',((row.p95_ms/old.p95_ms-1)*100).toFixed(1)+'%',old.draw_calls+' → '+row.draw_calls]){const td=document.createElement('td');td.textContent=value;tr.append(td)}document.getElementById('metrics').append(tr)}
document.getElementById('startup').textContent='World setup: '+before.world_setup_ms+' → '+after.world_setup_ms+' ms. Captured checks: '+after.checks+', failures: '+after.failures+'.';
const routes=walk.routes||[],walkSelect=document.getElementById('walkRegion'),walkFrame=document.getElementById('walkFrame'),play=document.getElementById('playWalk');let timer=null;
function stopWalk(){if(timer)clearInterval(timer);timer=null;play.textContent='Play walk'}
function showWalk(){const route=routes.find(x=>x.id===walkSelect.value);if(!route)return;document.getElementById('walkImage').src='walk/walk-'+route.id+'-'+String(walkFrame.value).padStart(3,'0')+'.png';document.getElementById('walkTime').textContent=(Number(walkFrame.value)/4).toFixed(2)+' s / '+route.walk.seconds.toFixed(1)+' s'}
for(const route of routes){const o=document.createElement('option');o.value=route.id;o.textContent=labels[route.id];walkSelect.append(o)}
walkSelect.onchange=()=>{stopWalk();const route=routes.find(x=>x.id===walkSelect.value);walkFrame.max=route.walk.frames-1;walkFrame.value=0;showWalk()};walkFrame.oninput=()=>{stopWalk();showWalk()};play.onclick=()=>{if(timer){stopWalk();return}play.textContent='Pause';timer=setInterval(()=>{walkFrame.value=(Number(walkFrame.value)+1)%(Number(walkFrame.max)+1);showWalk()},250)};document.getElementById('walkSection').hidden=!routes.length;if(routes.length)walkSelect.onchange();
</script></html>'''
page = page.replace('src="walk/lantern-workshop-', 'src="' + interior + '/lantern-workshop-')
if (root / 'fen-perf' / 'manifest.json').exists():
    page = page.replace('<p class="note">Changes above 10%', '<p class="note">Follow-up: the Fen’s 2.223 ms primary p95 did not repeat; eight further shown windows measured 1.814–1.852 ms. Added composition cost averaged about 0.069 ms p95 in a shown/hidden comparison. <a href="fen-perf/manifest.json">Repeated measurements</a>. Early approach hitches remain documented in the report.</p><p class="note">Changes above 10%')
(root / 'index.html').write_text(page.replace('__BEFORE__', json.dumps(before)).replace('__AFTER__', json.dumps(after)).replace('__WALK__', json.dumps(walk)), encoding='utf8')
print(root / 'index.html')
