"""Build the local Strange Frontier evidence gallery from finished manifests."""
import json
from pathlib import Path

root=Path(__file__).resolve().parents[2]/'build'/'strange-frontier'
art=json.loads((root/'art'/'manifest.json').read_text())
world=json.loads((root/'world'/'manifest.json').read_text()) if (root/'world'/'manifest.json').exists() else {}
for region in world.get('regions',[]):
    region['has_cave']=(root/'world'/(region['id']+'-cave.png')).exists()
page='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>The Strange Frontier · Gameplay review</title><style>
*{box-sizing:border-box}body{margin:0;background:#171c19;color:#e8e2d1;font:16px/1.55 system-ui,sans-serif}main{max-width:1480px;margin:auto;padding:32px}h1{font:600 43px/1.15 Georgia,serif;margin:8px 0 17px}h2{font:500 29px/1.2 Georgia,serif;margin:32px 0 12px}p{max-width:980px;color:#b8c1b1}.eyebrow{font-size:12px;letter-spacing:.12em;text-transform:uppercase;color:#c5c597}nav,.controls{display:flex;gap:9px;flex-wrap:wrap;margin:18px 0}button,select{background:#293629;color:#eee8d9;border:1px solid #506045;border-radius:5px;padding:9px 15px;cursor:pointer}button.active,button:hover{background:#728163}.hero{padding:12px;border:1px solid #40523f;background:#121915;border-radius:10px}.hero img{display:block;width:100%;aspect-ratio:1.6;object-fit:contain;border-radius:5px}.controls label{display:flex;align-items:center;gap:8px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:18px;margin-top:24px}article{background:#212c23;border:1px solid #415340;border-radius:8px;padding:15px}article img{width:100%;display:block;border-radius:5px}article h3{margin:0 0 12px;font-size:20px}article p{font-size:14px}.note{font-size:13px;color:#a9b5a1}a{color:#d3d9b0}table{width:100%;border-collapse:collapse;background:#202a22}td,th{padding:10px 14px;border-bottom:1px solid #41513f;text-align:left}th{font-weight:500;color:#c6cda9}input{accent-color:#bac797}.stats{display:flex;gap:14px;flex-wrap:wrap;margin:22px 0}.stat{padding:12px 20px;background:#29362b;border-radius:6px}.stat b{display:block;font-size:24px}iframe{display:block;width:100%;height:720px;border:1px solid #40523f;border-radius:8px}details{margin:22px 0}summary{cursor:pointer;color:#d5dcb5}</style><main>
<div class="eyebrow">Wroughtwild · Owner-approved D-029 intensive · 6 September 2026</div><h1>The Strange Frontier</h1><p>Three broad places to explore, five physical finds, and useful objects that show what those finds can do. These are captures from Godot's gameplay renderer, with a separate small authoring study and a real signal-driven cargo demonstration.</p>
<section id="worldSection"><nav id="regions"></nav><div class="hero"><img id="worldView" alt="Generated Strange Frontier region in normal gameplay"><div class="controls"><button id="day">Daylight</button><button id="dusk">Matched dusk</button><button id="cave">Cave approach</button><button id="play">Play approach</button><label>Walk <input id="walk" type="range" min="0" value="0"><span id="frame"></span></label></div></div><p class="note">The camera follows the generated approach at ordinary movement speed and 1.65 m eye height. Four saved frames per second show the route; these scripted walks do not certify discovery excitement or substitute for a normal play session.</p></section>
<div class="stats" id="stats"></div><h2>From clue to intact find</h2><p>Contextual work exposes a core without a class or reflex gate. The housing and clue trail remain when the finite specimen is removed.</p><div class="grid" id="finds"></div>
<h2>Water at walking height</h2><div class="hero"><img src="world/lantern_fen-pools.png" alt="Supported shallow Lantern Fen pools with reed growth and irregular banks"></div><h2>A find brought home</h2><div class="grid"><article><h3>Daylight workshop</h3><img src="world/lantern-workshop-day.png" alt="Lanternheart lamp in an ordinary resinheart workshop"></article><article><h3>The same room at dusk</h3><img src="world/lantern-workshop-dusk.png" alt="Local warm lamp light in the workshop at dusk"></article></div>
<h2>A signal that moves something</h2><p>The drum is wound, cargo is loaded, and a Stormglass lever requests the winch's existing energy. The basket moves to the supported landing and its contents transfer once.</p><iframe src="contraptions/index.html" title="Recorded actual winch and signal interaction" loading="lazy"></iframe>
<details><summary>Small authored pocket and reusable asset kit</summary><p>This flat study establishes the shared asset, work-stage and fixture look before testing actual generated geography.</p><div class="grid"><article><h3>Lantern pocket</h3><img src="art/lantern-pocket-day.png" alt="Authored hollow-trunk Lanternheart pocket"></article><article><h3>Useful objects</h3><img src="art/contraption-kit.png" alt="Lamp, winch, landing, lever, sorter and bellows asset kit"></article><article><h3>Root arch</h3><img src="art/rootvault-arch.png" alt="Curved branching root arch with open chamber"></article></div></details>
<h2>Measured art cost</h2><p class="note">Exact same settled camera, profile, terrain and intact resources, with regional dressing shown and then hidden. Each sample discards 30 warmup frames and measures 150. This isolates dressing cost; the separate terrain report compares v2/v3 startup and actual streaming travel. Results describe this RTX 5090 machine.</p><table><thead><tr><th>Region</th><th>Median: hidden → shown</th><th>p95: hidden → shown</th><th>Median / p95 change</th></tr></thead><tbody id="performance"></tbody></table>
<p><a href="world/manifest.json">World capture manifest</a> · <a href="art/manifest.json">Authored art checks</a> · <a href="../../docs/art/strange-frontier-2026-09-06.md">Implementation and limitations</a> · <a href="../../docs/art/strange-generation-2026-09-06.md">Generation and streaming review</a></p>
</main><script>
const world=__WORLD__,art=__ART__;
const labels={rootvault_wildwood:'Rootvault Wildwood',lantern_fen:'Lantern Fen',glasswind_uplands:'Glasswind Uplands'};
let selected=(world.regions||[])[0],timer=null;const view=document.getElementById('worldView'),slider=document.getElementById('walk');
function stop(){if(timer)clearInterval(timer);timer=null;document.getElementById('play').textContent='Play approach'}
function show(name){view.src='world/'+name+'.png'}
function walk(){show('walk-'+selected.id+'-'+String(slider.value).padStart(3,'0'));document.getElementById('frame').textContent=(Number(slider.value)+1)+' / '+selected.walk.frames}
for(const region of world.regions||[]){const b=document.createElement('button');b.textContent=labels[region.id]||region.id;b.onclick=()=>{stop();selected=region;document.getElementById('cave').hidden=!region.has_cave;slider.max=region.walk.frames-1;slider.value=0;show(region.id+'-day');document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x===b))};document.getElementById('regions').append(b);if(region===selected)b.click()}
if(!selected)document.getElementById('worldSection').hidden=true;
document.getElementById('day').onclick=()=>{stop();show(selected.id+'-day')};document.getElementById('dusk').onclick=()=>{stop();show(selected.id+'-dusk')};document.getElementById('cave').onclick=()=>{stop();show(selected.id+'-cave')};slider.oninput=()=>{stop();walk()};document.getElementById('play').onclick=()=>{if(timer){stop();return}document.getElementById('play').textContent='Pause';timer=setInterval(()=>{slider.value=(Number(slider.value)+1)%selected.walk.frames;walk()},250)};
const finds=[['lanternheart','Lanternheart','Empty papery husks lead to a shaded warm heart. Its first use is a reusable household lamp.'],['thrumroot','Thrumroot','A braced deadfall exposes a coiled root. The same tension becomes a hand-wound cargo drum.'],['stormglass','Stormglass','Milky tubes follow old lightning scars. Their pulse requests work but supplies no energy.'],['pullstone','Pullstone','Dark iron grit clings to the nodule. A hand-fed chute separates ferrous ingredients into a tray.'],['ventlung','Ventlung','A breathing membrane sits in an old mineral casing. Hand-primed bellows deliver an impact response.']];
for(const[id,label,description]of finds){const a=document.createElement('article');const h=document.createElement('h3');h.textContent=label;a.append(h);const image=document.createElement('img');image.src='world/find-'+id+'.png';image.alt=label+' in the generated world';a.append(image);const controls=document.createElement('div');controls.className='controls';for(const[prefix,text]of [['find','Intact'],['worked','Worked'],['empty','Aftermath']]){const b=document.createElement('button');b.textContent=text;b.onclick=()=>image.src='world/'+prefix+'-'+id+'.png';controls.append(b)}a.append(controls);const p=document.createElement('p');p.textContent=description;a.append(p);document.getElementById('finds').append(a)}
for(const[label,value]of [['Authored art checks',art.checks+' / '+art.failures+' failures'],['Generated world checks',(world.checks||'Pending')+' / '+(world.failures||0)+' failures'],['Reusable authored assets',art.asset_count],['World setup',world.world_setup_ms?world.world_setup_ms+' ms':'Pending']]){const e=document.createElement('div');e.className='stat';e.textContent=label;const b=document.createElement('b');b.textContent=value;e.append(b);document.getElementById('stats').append(e)}
for(const region of world.regions||[]){const row=document.createElement('tr');for(const value of [labels[region.id],region.dressing_hidden.median.toFixed(3)+' → '+region.with_dressing.median.toFixed(3)+' ms',region.dressing_hidden.p95.toFixed(3)+' → '+region.with_dressing.p95.toFixed(3)+' ms',region.change_percent.median.toFixed(2)+'% / '+region.change_percent.p95.toFixed(2)+'%']){const cell=document.createElement('td');cell.textContent=value;row.append(cell)}document.getElementById('performance').append(row)}
</script></html>'''
(root/'index.html').write_text(page.replace('__ART__',json.dumps(art)).replace('__WORLD__',json.dumps(world)),encoding='utf8')
print(root/'index.html')
