"""Run only through Blender: deterministic building pieces in Godot metres.

Blender (x, y, z) = Godot (x, -z, y); glTF's Y-up export restores Godot axes.
Each piece stays centred on its existing PieceMesh pose, with unit scale.
"""
import json
import math
from pathlib import Path
import random
import re
import sys

import bpy
from mathutils import Vector

project, output = map(Path, sys.argv[sys.argv.index('--') + 1:])
config = json.loads((Path(__file__).resolve().parents[1] / 'study.json').read_text())
construction = json.loads((project / 'data/tuning/construction.json').read_text())
shapes = {s['id']: s for s in construction['shapes']}
palette_source = (project / 'game/art/building_look.gd').read_text()
timber_hex = re.search(r'@export var timber := Color\("([0-9a-f]+)"\)', palette_source)[1]
frame_shade = float(re.search(r'@export var frame_shade := ([0-9.]+)', palette_source)[1])
rng = random.Random(config['seed'])
bpy.ops.object.select_all(action='SELECT')
bpy.ops.object.delete(use_global=False)


def linear(value):
    return value / 12.92 if value <= 0.04045 else ((value + 0.055) / 1.055) ** 2.4


base = [int(timber_hex[i:i+2], 16) / 255 for i in (0, 2, 4)]


def material(name, factor):
    mat = bpy.data.materials.new(name)
    mat.use_nodes = True
    color = tuple(linear(min(1, c * factor)) for c in base) + (1,)
    mat.diffuse_color = color
    shader = mat.node_tree.nodes.get('Principled BSDF')
    shader.inputs['Base Color'].default_value = color
    shader.inputs['Roughness'].default_value = config['roughness']
    if name != 'Neutral study floor':
        # Bake colour into portable pixels: no Blender-only shader dependency.
        image = bpy.data.images.new(name + ' grain', width=128, height=512)
        pixels = []
        for v in range(512):
            for u in range(128):
                bend = math.sin(v * .016) * 1.4 + math.sin(v * .041 + u * .013) * .7
                fibre = math.sin((u + bend) * 1.83) * .45 + math.sin((u + bend) * .31) * .35
                pore = math.sin(u * 71.3 + v * 18.7) * .2
                shade = 1 + (fibre + pore) * config['grain_strength']
                # Generated byte-buffer pixels are encoded sRGB values.
                pixels.extend([min(1, c * factor * shade) for c in base] + [1])
        # Colour textures must export as sRGB; glTF decodes base colour as sRGB.
        image.colorspace_settings.name = 'sRGB'
        image.pixels.foreach_set(pixels)
        image.pack()
        texture = mat.node_tree.nodes.new('ShaderNodeTexImage')
        texture.image = image
        mat.node_tree.links.new(texture.outputs['Color'], shader.inputs['Base Color'])
    return mat


boards = [material('Weathered timber %02d' % i, 1 + rng.uniform(-config['colour_variation'], config['colour_variation'])) for i in range(8)]
frame = material('Dark structural timber', frame_shade)


def xyz(godot):
    return (godot[0], -godot[2], godot[1])


def box(name, center, size, mat, bevel=True):
    bpy.ops.mesh.primitive_cube_add(size=1, location=xyz(center))
    obj = bpy.context.object
    obj.name = name
    obj.dimensions = (size[0], size[2], size[1])
    bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
    obj.data.materials.append(mat)
    if bevel:
        mod = obj.modifiers.new('Worn arris', 'BEVEL')
        mod.width = config['edge_bevel_metres']
        mod.segments = 1
        bpy.ops.object.modifier_apply(modifier=mod.name)
        obj.modifiers.new('Weighted corner normals', 'WEIGHTED_NORMAL')
    # Grain follows the longest axis on each face, including beam end-grain faces.
    uv = obj.data.uv_layers.active
    for polygon in obj.data.polygons:
        normal_axis = max(range(3), key=lambda axis: abs(polygon.normal[axis]))
        face_axes = [axis for axis in range(3) if axis != normal_axis]
        long_axis = max(face_axes, key=lambda axis: obj.dimensions[axis])
        short_axis = next(axis for axis in face_axes if axis != long_axis)
        for index in polygon.loop_indices:
            vertex = obj.data.vertices[obj.data.loops[index].vertex_index].co
            uv.data[index].uv = (vertex[short_axis] / obj.dimensions[short_axis] + .5,
                                 vertex[long_axis] / obj.dimensions[long_axis] + .5)
    return obj


def export(path, objects):
    bpy.ops.object.select_all(action='DESELECT')
    for obj in objects:
        obj.hide_set(False)
        obj.select_set(True)
    bpy.context.view_layer.objects.active = objects[0]
    bpy.ops.export_scene.gltf(filepath=str(path), export_format='GLB', use_selection=True,
                             export_yup=True, export_apply=True, export_cameras=False,
                             export_lights=False)


def bounds(objects):
    points = [obj.matrix_world @ Vector(p) for obj in objects for p in obj.bound_box]
    godot = [(p.x, p.z, -p.y) for p in points]
    return [[min(p[i] for p in godot) for i in range(3)],
            [max(p[i] for p in godot) for i in range(3)]]


assets = {}
report = {'seed': config['seed'], 'palette_source': 'game/art/building_look.gd',
          'dimensions_source': 'data/tuning/construction.json', 'assets': {},
          'status': 'isolated study; normal game still uses existing meshes and collisions'}
for piece in ('wall_panel', 'pillar', 'beam'):
    width, height, depth = shapes[piece]['size_m']
    objects = []
    if piece == 'wall_panel':
        # Solid recessed backing means shallow board seams do not reveal daylight.
        objects.append(box('Wall backing', (0, 0, 0), (width, height, depth * .65), frame, False))
        count = config['board_count']
        rail = height * config['frame_fraction']
        for side in (-1, 1):
            for i in range(count):
                plank_width = width / count - config['seam_metres']
                x = -width / 2 + width / count * (i + .5)
                objects.append(box('Wall board %s %s' % (side, i),
                                   (x, 0, side * depth * .405),
                                   (plank_width, height - 2 * rail, depth * .19), boards[i]))
            for y in (-height / 2 + rail / 2, height / 2 - rail / 2):
                objects.append(box('Wall rail', (0, y, side * depth * .405),
                                   (width, rail, depth * .19), frame))
    else:
        objects.append(box(piece, (0, 0, 0), (width, height, depth), frame))
    bpy.context.view_layer.update()
    visual_bounds = bounds(objects)
    for axis, extent in enumerate((width, height, depth)):
        assert abs(visual_bounds[0][axis] + extent / 2) < 1e-5, (piece, visual_bounds)
        assert abs(visual_bounds[1][axis] - extent / 2) < 1e-5, (piece, visual_bounds)
    for obj in objects:
        assert all(abs(s - 1) < 1e-6 for s in obj.scale)
    export(output / (piece + '.glb'), objects)
    proxy = box(piece + '-convcolonly', (0, 0, 0), (width, height, depth), frame, False)
    export(output / (piece + '_collision.glb'), [proxy])
    bpy.context.view_layer.update()
    report['assets'][piece] = {'size_godot_metres': [width, height, depth],
                              'visual_bounds': visual_bounds, 'collision_bounds': bounds([proxy]),
                              'mesh_parts': len(objects),
                              'triangles': sum(len(p.vertices) - 2 for o in objects for p in o.data.polygons),
                              'collision': 'one box-equivalent convex proxy; no decorative collision'}
    bpy.data.objects.remove(proxy, do_unlink=True)
    assets[piece] = objects

# Keep sources in their own hidden collection at the origin for editing.
source = bpy.data.collections.new('SOURCE - centred metre assets')
bpy.context.scene.collection.children.link(source)
for objects in assets.values():
    for obj in objects:
        for collection in list(obj.users_collection):
            collection.objects.unlink(obj)
        source.objects.link(obj)
source.hide_render = True
source.hide_viewport = True


def instance(piece, position, angle=0):
    root = bpy.data.objects.new(piece + ' placement', None)
    bpy.context.scene.collection.objects.link(root)
    root.location = xyz(position)
    root.rotation_euler.z = angle
    for obj in assets[piece]:
        clone = obj.copy()
        clone.data = obj.data
        bpy.context.scene.collection.objects.link(clone)
        clone.parent = root
    return root


# A two-metre-high wall meets its return on the same one-metre grid.
for y in (.5, 1.5):
    for x in (0, 1, 2):
        instance('wall_panel', (x, y, 0))
    for z in (.5, 1.5):
        instance('wall_panel', (2.5, y, z), math.pi / 2)
    # Explicit placed posts in this display, not new automatic colliding trims.
    for x, z in ((-.5, 0), (2.5, 0), (2.5, 2)):
        instance('pillar', (x, y, z))
for x in (0, 1, 2):
    instance('beam', (x, 2, 0))
for z in (.5, 1.5):
    instance('beam', (2.5, 2, z), math.pi / 2)
# Review-only timber joint cap hides coincident beam end faces at the turn.
# It is decorative, not an exported piece or a new colliding lattice element.
box('Study corner joint cap', (2.5, 2.22, 0), (.42, .04, .42), frame)
instance('wall_panel', (-2.0, .75, 0))
instance('pillar', (-2.9, .5, 0))
instance('beam', (-2.0, .2, 1.0))

ground = material('Neutral study floor', .43)
box('Review floor - not exported', (0, -.05, .5), (200, .1, 200), ground, False)
scene = bpy.context.scene
scene.render.engine = 'CYCLES'
scene.cycles.samples = 24
scene.cycles.use_denoising = True
scene.render.resolution_x = 1440
scene.render.resolution_y = 960
scene.render.resolution_percentage = 100
scene.world.color = (.22, .22, .22)
scene.view_settings.view_transform = 'AgX'


def aim(obj, point):
    obj.rotation_euler = (Vector(point) - obj.location).to_track_quat('-Z', 'Y').to_euler()


for name, location, energy, size in [('Daylight', (-3, -4, 7), 1700, 5), ('Fill', (4, 1, 5), 1000, 4)]:
    light = bpy.data.lights.new(name, 'AREA')
    light.energy, light.shape, light.size = energy, 'DISK', size
    obj = bpy.data.objects.new(name, light)
    scene.collection.objects.link(obj)
    obj.location = location
    aim(obj, (0, 0, 1))
camera_data = bpy.data.cameras.new('Study camera')
camera = bpy.data.objects.new('Study camera', camera_data)
scene.collection.objects.link(camera)
camera.location = (-7, -10, 6)
aim(camera, (0, -.4, .8))
camera_data.type = 'ORTHO'
camera_data.ortho_scale = 8.3
scene.camera = camera
scene.render.filepath = str(output / 'building-study.png')
bpy.ops.wm.save_as_mainfile(filepath=str(output / 'building-study.blend'))
bpy.ops.render.render(write_still=True)
(output / 'report.json').write_text(json.dumps(report, indent=2), encoding='utf-8')
print('WROUGHTWILD_STUDY_OK ' + str(output))
