extends SceneTree
const Adapter := preload("res://native_state.gd")
var checks := 0
var failures: Array[String] = []
func check(value: bool, label: String) -> void:
	checks += 1
	if not value: failures.append(label); push_error(label)
func _initialize() -> void:
	call_deferred("run")
func run() -> void:
	var a := Adapter.new()
	if "--restart" in OS.get_cmdline_user_args():
		a.load_checkpoint("user://held.json")
		var ledger := a.sim.contraption_save()
		a.tick(100.0)
		check(a.sim.contraption_save() == ledger, "fresh process retains paused fractional escrow")
		check(a.view().reserved_heat == 1 and a.view().clay_held == 8 and a.view().stroke_held == 1 and a.view().progress == 2.25, "restart exact heat/clay/stroke/time")
		check(a.act("resume").ok, "restart resume")
		a.tick(5.75)
		check(a.view().output == 12 and a.view().heat == 3 and a.view().reserved_heat == 0, "restart completes paid firing exactly once")
		ledger = a.sim.contraption_save(); a.tick(100.0)
		check(a.sim.contraption_save() == ledger and not a.view().working, "no repeated success or unpaid continuation")
		finish(); return
	var v := a.view()
	check(v.heat == 3 and v.reserved_heat == 1 and v.progress == 2.25 and v.output == 8, "published paid checkpoint exact")
	check(v.source_ready and v.lot == 7 and v.raw_claim == 0, "last native Red lot ready")
	var starting_sources := a.sim.leyline_save()
	var ledger := a.sim.contraption_save()
	a.tick(50.0)
	check(a.sim.contraption_save() == ledger and not a.view().working, "stored/paused heat cannot animate work or produce")
	check(a.sim.leyline_save() == starting_sources, "ready source banks no formation credit")
	var pack := a.sim.inventory()
	check(not a.act("heat").ok and a.sim.inventory() == pack and a.sim.contraption_save() == ledger, "reserved return slot refuses charge without taking salt")
	for i in 4:
		check(a.act("work").ok, "real extraction step %d" % (i+1))
		check(a.view().source_work == (i+1)%4, "manual work follows native stage")
	check(a.view().raw_claim == 16 and not a.view().source_ready and a.view().salt_owned == 2, "released 16 stay source-owned")
	var claim := a.sim.leyline_save()
	check(not a.act("work").ok and a.sim.leyline_save() == claim, "cannot extract beyond an uncollected claim")
	a.checkpoint("user://claim.json")
	a.load_checkpoint("user://claim.json")
	check(a.sim.leyline_save() == claim and a.view().raw_claim == 16, "claim reload exact without reroll")
	check(a.act("collect").moved == 16 and a.view().salt_owned == 18 and a.view().raw_claim == 0, "successful collection transfers exactly one owned lot")
	pack = a.sim.inventory(); claim = a.sim.leyline_save()
	check(not a.act("collect").ok and a.sim.inventory() == pack and a.sim.leyline_save() == claim, "second collection cannot duplicate")
	check(not a.view().source_ready and a.view().source_state == "Forming", "exhausted source loses ready light")
	a.paused = true; a.tick(700.0)
	check(a.sim.leyline_save() == claim and not a.view().working, "review pause freezes formation and work")
	a.paused = false; a.source_blocked = true; a.tick(700.0)
	check(not a.view().source_ready and a.view().formation == 600.0, "obstruction caps credit and prevents ready state")
	a.source_blocked = false; a.tick(.01)
	check(a.view().source_ready and a.view().lot == 0, "native unblocked formation re-arms exactly one source")
	# Restart original paid workshop independently of the formation branch.
	a.load_checkpoint("res://paid-checkpoint.json")
	a.checkpoint("user://held.json")
	check(a.act("resume").ok, "resume existing held firing")
	a.physical_ready = false; ledger = a.sim.contraption_save(); a.tick(50.0)
	check(a.sim.contraption_save() == ledger and not a.view().working, "blocked thermal span freezes fraction and no work pulse")
	a.physical_ready = true; a.tick(1.0)
	check(a.view().working and a.view().progress == 3.25, "work cue requires actual native progress")
	check(a.act("pause").ok, "manual pause")
	ledger = a.sim.contraption_save(); a.tick(50.0)
	check(a.sim.contraption_save() == ledger and not a.view().working, "manual pause retains exact ownership")
	check(a.act("cancel").ok and a.view().heat == 4 and a.view().reserved_heat == 0, "cancel returns heat once")
	var f := a.sim.contraption_state(Adapter.FEEDER)
	check(f.energy == 1 and f.input.get("raw_clay",0) == 8, "cancel returns exact clay and stroke")
	ledger = a.sim.contraption_save()
	check(not a.act("cancel").ok and a.sim.contraption_save() == ledger, "second cancel cannot return more heat")
	check(a.act("start").ok, "restart returned paid inputs")
	a.tick(8.0)
	check(a.view().output == 12 and a.view().heat == 3 and a.view().reserved_heat == 0, "one paid firing produces four real bricks")
	check(a.act("heat").ok and a.view().heat == 4 and a.view().salt_owned == 0, "two real salt charge exactly one heat")
	ledger = a.sim.contraption_save();pack = a.sim.inventory()
	check(not a.act("heat").ok and a.sim.contraption_save() == ledger and a.sim.inventory() == pack, "full store cannot take more salt")
	check(not a.act("start").ok and a.sim.contraption_save() == ledger, "heat alone cannot replace clay or mechanical winding")
	# Capacity branches are isolated test arrangements, never art-review inventory.
	a.load_checkpoint("res://paid-checkpoint.json")
	for i in 4: a.act("work")
	a.sim.add_material("red_salt",126)
	claim = a.sim.leyline_save(); pack = a.sim.inventory()
	check(not a.act("collect").ok and a.sim.leyline_save() == claim and a.sim.inventory() == pack, "full pack preserves source-owned pieces")
	check(a.sim.consume_material("red_salt",3), "capacity branch frees three units")
	check(a.act("collect").moved == 3 and a.view().raw_claim == 13 and a.view().salt_owned == 128, "partial capacity transfers three and retains thirteen")
	a.checkpoint("user://partial.json"); claim = a.sim.leyline_save()
	a.load_checkpoint("user://partial.json")
	check(a.sim.leyline_save() == claim and a.view().raw_claim == 13, "partial claim survives exact reload")
	# Reach a rare claim using actual fixed manifestation outcomes and actual
	# active formation time. No outcome is edited or re-rolled on load.
	a.load_checkpoint("res://paid-checkpoint.json")
	var found_rare := false
	for lot in 160:
		var carried: int = a.sim.material_count("red_salt")
		if carried > 0: a.sim.consume_material("red_salt", carried)
		if a.view().lot == a.view().lots: a.tick(600.0)
		for step in 4: a.act("work")
		if a.view().rare_claim > 0:
			found_rare = true
			check(a.view().raw_claim == 16, "native rare and raw share a released claim")
			a.act("collect")
			check(a.view().raw_claim == 0 and a.view().rare_claim == 1 and not a.view().source_ready, "raw collection cannot hide or consume a held rare catalyst")
			a.checkpoint("user://rare-held.json");claim=a.sim.leyline_save()
			a.load_checkpoint("user://rare-held.json")
			check(a.sim.leyline_save()==claim and a.view().rare_claim==1, "rare-only claim reload remains exact")
			check(a.act("collect_rare").moved==1 and a.view().rare_claim==0, "rare claim transfers once through native collection")
			break
		a.act("collect")
	check(found_rare, "fixed Red stream contains a rare claim within the bounded test")
	finish()
func finish() -> void:
	var report := {"checks":checks,"failures":failures,"fresh_process":"--restart" in OS.get_cmdline_user_args()}
	var file := FileAccess.open("user://native-restart.json" if report.fresh_process else "user://native-checks.json",FileAccess.WRITE)
	file.store_string(JSON.stringify(report,"\t"))
	print("ART04_NATIVE_CHECKS ", JSON.stringify(report))
	quit(0 if failures.is_empty() else 1)
