extends Node3D
## Verify imported presentation contracts independently of world placement.
var checks:=0
var failures:=0

func check(ok: bool, label: String) -> void:
	checks+=1
	if not ok:
		failures+=1
		printerr("FAIL CATACLYSM ART: ",label)

func _ready() -> void:
	var manifest: Dictionary=JSON.parse_string(FileAccess.get_file_as_string("res://assets/authored/cataclysm_manifest.json"))
	check(manifest.assets.size()==14,"bounded environment kit has fourteen named assets")
	var frames: Array=[]
	for id: String in manifest.assets:
		var data: Dictionary=manifest.assets[id]
		var mesh:=AuthoredAssets.mesh_for(id)
		check(mesh!=null and mesh.get_surface_count()>0,"curated asset imports "+id)
		if mesh==null:continue
		var expected_min:=Vector3(data.bounds_min[0],data.bounds_min[1],data.bounds_min[2])
		var expected_max:=Vector3(data.bounds_max[0],data.bounds_max[1],data.bounds_max[2])
		var bounds:=mesh.get_aabb()
		check(bounds.position.distance_to(expected_min)<.004 and bounds.end.distance_to(expected_max)<.004,"actual imported bounds match placement manifest "+id)
		var colour_min:=Vector3.INF
		var colour_max:=-Vector3.INF
		for surface in mesh.get_surface_count():
			var material:=mesh.surface_get_material(surface) as StandardMaterial3D
			check(material!=null and material.albedo_texture!=null,"embedded original grain survives import")
			check(material!=null and material.vertex_color_use_as_albedo,"regional vertex colour survives import")
			var arrays:=mesh.surface_get_arrays(surface)
			check(arrays[Mesh.ARRAY_VERTEX].size()>0 and arrays[Mesh.ARRAY_COLOR].size()>0,"nonempty mesh and colour arrays")
			for colour: Color in arrays[Mesh.ARRAY_COLOR]:
				var rgb:=Vector3(colour.r,colour.g,colour.b)
				colour_min=colour_min.min(rgb)
				colour_max=colour_max.max(rgb)
			# Imported StandardMaterial colours are exposed in sRGB; glTF's
			# emissiveFactor and the authored strength are linear energy.
			var emission:=material.emission.srgb_to_linear() if material!=null else Color.WHITE
			check(material!=null and maxf(emission.r,maxf(emission.g,emission.b))*material.emission_energy_multiplier<.3,"augmentation stays below a broad bright emission")
		# Presence alone missed an all-white COLOR_0 generated by exporter
		# material inference. Compare actual runtime RGB to the source palette.
		var palette_min: Array=data.get("colour_linear_min",[])
		var palette_max: Array=data.get("colour_linear_max",[])
		check(palette_min.size()==3 and palette_max.size()==3,"manifest records authored palette range "+id)
		if palette_min.size()==3 and palette_max.size()==3:
			var low:=Vector3(palette_min[0],palette_min[1],palette_min[2])
			var high:=Vector3(palette_max[0],palette_max[1],palette_max[2])
			check(colour_min.distance_to(low)<.012 and colour_max.distance_to(high)<.012,"runtime COLOR_0 matches authored palette rather than synthetic white "+id)
		var source: PackedScene=load("res://assets/authored/"+id+".glb")
		var imported:=source.instantiate()
		check(imported.find_children("*","CollisionObject3D",true,false).is_empty(),"authoring exports no gameplay bodies")
		# Runtime scenery discards the imported scene and retains only its mesh.
		# Compare that exact path with the scene's active materials; a material
		# stored as an instance override must survive flattening and cache reuse.
		var expected_materials: Array[Material]=[]
		_source_materials(imported,expected_materials)
		check(expected_materials.size()==mesh.get_surface_count(),"runtime surface count matches imported scene "+id)
		var cached:=AuthoredAssets.mesh_for(id)
		check(cached==mesh,"runtime cache reuses the verified mesh "+id)
		var visible:=MeshInstance3D.new()
		visible.mesh=cached
		var scaled:=AuthoredAssets.scaled_mesh(id,Vector3(.85,.85,.85))
		for surface in mini(expected_materials.size(),mesh.get_surface_count()):
			var expected:=expected_materials[surface]
			check(expected!=null and mesh.surface_get_material(surface)==expected,"runtime mesh preserves imported active material "+id+" surface "+str(surface))
			check(visible.get_active_material(surface)==expected,"new runtime instance renders the imported active material "+id+" surface "+str(surface))
			check(scaled.surface_get_material(surface)==expected,"scaled runtime mesh preserves imported active material "+id+" surface "+str(surface))
		visible.free()
		imported.free()
		if data.get("clear_aperture")!=null:
			var body:=StaticBody3D.new()
			var shape:=CollisionShape3D.new()
			shape.shape=mesh.create_trimesh_shape()
			body.add_child(shape)
			add_child(body)
			body.position.x=frames.size()*8.0
			frames.append({"body":body,"aperture":data.clear_aperture,"id":id,"bounds":bounds})
	_verify_override_path()
	for i in 3:await get_tree().physics_frame
	for frame: Dictionary in frames:
		var centre: Vector3=frame.body.position
		var opening: Dictionary=frame.aperture
		for x in [-.48,-.24,0.0,.24,.48]:
			for y in [.12,.40,.72,.98]:
				var at:=centre+Vector3(x*float(opening.width_m),y*float(opening.height_m),0)
				var ray:=PhysicsRayQueryParameters3D.create(at+Vector3(0,0,2),at-Vector3(0,0,2))
				check(get_world_3d().direct_space_state.intersect_ray(ray).is_empty(),"frame aperture is genuinely clear "+String(frame.id))
		var post:=centre+Vector3(frame.bounds.end.x-.2,.9,0)
		var ray:=PhysicsRayQueryParameters3D.create(post+Vector3(0,0,2),post-Vector3(0,0,2))
		check(not get_world_3d().direct_space_state.intersect_ray(ray).is_empty(),"frame side ray proves collision review is active")
	print("CATACLYSM_ART_REVIEW %d checks, %d failures"%[checks,failures])
	get_tree().quit(0 if failures==0 else 1)

func _source_materials(node: Node, output: Array[Material]) -> void:
	if node is MeshInstance3D:
		var visual:=node as MeshInstance3D
		for surface in visual.mesh.get_surface_count():
			var active:=visual.get_active_material(surface)
			output.append(active)
	for child in node.get_children():_source_materials(child,output)

func _verify_override_path() -> void:
	# Current imports store materials on the mesh. Inject an instance override
	# only into the in-memory PackedScene to exercise the loader's alternate
	# import representation. Restore that scene and cache before continuing;
	# no asset, import settings or source file is written by this regression.
	var id:="cataclysm_augmentation_inlay"
	var source:=load("res://assets/authored/"+id+".glb") as PackedScene
	var original:=source.instantiate()
	var changed:=source.instantiate()
	var instances: Array=[]
	AuthoredAssets._collect_instances(changed,Transform3D.IDENTITY,instances)
	check(instances.size()==1 and instances[0].transform.is_equal_approx(Transform3D.IDENTITY),"override regression exercises the single-mesh identity fast path")
	if instances.size()!=1:
		original.free()
		changed.free()
		return
	var visual: MeshInstance3D=instances[0].instance
	var original_material:=visual.mesh.surface_get_material(0)
	var override:=StandardMaterial3D.new()
	override.albedo_color=Color(.21,.39,.56)
	visual.set_surface_override_material(0,override)
	check(source.pack(changed)==OK,"temporary instance override is packed in memory")
	AuthoredAssets._meshes.erase(id)
	var runtime:=AuthoredAssets.mesh_for(id)
	check(runtime.surface_get_material(0)==override,"runtime loader preserves a real instance override after imported scene disposal")
	check(visual.mesh.surface_get_material(0)==original_material,"runtime override preservation does not mutate shared imported mesh materials")
	check(source.pack(original)==OK,"temporary packed scene is restored")
	AuthoredAssets._meshes.erase(id)
	check(AuthoredAssets.mesh_for(id).surface_get_material(0)==original_material,"restored runtime mesh uses the original material")
	original.free()
	changed.free()
