extends "res://tests/living_frontier_wave2_flow.gd"
const GREEN_PENDING := "user://lf2-green-pending.json"
const GREEN_COMPLETE := "user://lf2-green-complete.json"

func _run_lf() -> void:
	var manager := SaveManager.new()
	if "--green-restore" in OS.get_cmdline_user_args():
		await restore_green()
		return _finish_lf()
	check(manager.read(LF2_PAUSED,player),"published Blue paused checkpoint migrates: "+manager.last_error)
	freeze_fixtures()
	var old_blue := fixture("blue_delay")
	check(old_blue!=null and machine(old_blue).pending_request and machine(old_blue).delay_paused and machine(old_blue).delay_seconds==.8,"migration keeps published pending request and exact pause/fraction")
	if not check(manager.read(LF2_COMPLETE,player),"continue the complete paid A workshop: "+manager.last_error): return _finish_lf()
	freeze_fixtures(); refresh_stations()
	var source := find_host("green_home_margin")
	if not check(source!=null and source.state().lot==0,"Green introduced once at fourth home margin"): return _finish_lf()
	await aim_at(source)
	check(source.supported(),"Green has physical source support")
	player.interact()
	for step in 4: await press(String(source.state().next_work))
	await snap("green-source")
	for item: String in source.state().claim.keys(): await press("Collect "+Hud.pretty(item))
	if not await gather("ventlung",1) or not await gather("thrumroot",1) or not await gather("raw_reed",2): return _finish_lf()
	if not await gather("iron_ore",4) or not await gather("wood",40): return _finish_lf()
	await aim_at(forge)
	if not craft("smelt_iron",2,forge): return _finish_lf()
	await aim_at(bench)
	if not craft("assemble_pressure_feeder",1,bench) or not craft("assemble_green_junction",1,bench): return _finish_lf()
	check(_sim().material_count("green_resin")==14,"Green utility consumes two real resin")
	if not await place_paid_kit("pressure_feeder_kit",forge.global_position+Vector3(-3,0,-2)): return _finish_lf()
	if not await place_paid_kit("green_junction_kit",player.spawn_position+Vector3(0,0,-4)): return _finish_lf()
	freeze_fixtures()
	var green := fixture("green_junction")
	var feeder := fixture("pressure_feeder")
	var blue := fixture("blue_delay")
	var drum := fixture("cargo_winch")
	var landing := fixture("winch_landing")
	var lever := fixture("stormglass_lever")
	print("LF2_PLACED green_junction ",green.global_position," feeder ",feeder.global_position)
	await aim_at(feeder)
	player.interact()
	await press("Drive / connections")
	await press("Choose forge / pocket")
	await press("Attach forge · hand-wound")
	check(machine(feeder).forge_key==forge.station_key,"feeder attaches real paid forge")
	await connect_control(blue,green,"Choose receiver")
	await connect_control(green,drum,"Choose first receiver")
	await aim_at(green)
	player.interact()
	await press("Choose second receiver")
	await press("Link this Pressure feeder")
	check(machine(green).second_link==feeder.machine_key,"normal second port selects feeder")
	check(not _sim().contraption_link_second(green.machine_key,drum.machine_key,true).ok,"duplicate receiver refuses without changing either port")
	if machine(drum).at_landing:
		await aim_at(drum); player.interact()
		await press("Wind the drum"); await press("Crank a trip")
		drum._physics_process(20)
	await aim_at(drum); player.interact()
	await press("Wind the drum"); await press("Load 10 wood")
	if not await prepare_firing(feeder): return _finish_lf()
	# One physically blocked branch must leave the other independently useful.
	var wall := StaticBody3D.new()
	var collider := CollisionShape3D.new()
	var shape := BoxShape3D.new(); shape.size=Vector3(.8,3,.8)
	collider.shape=shape; wall.add_child(collider); add_child(wall)
	wall.global_position=green.cable_anchor().lerp(drum.cable_anchor(),.5)
	for frame in 2: await get_tree().physics_frame
	check(not green.span_clear(),"actual first-branch obstruction")
	await aim_at(lever); player.interact(); await press("Strike the lever")
	blue._physics_process(3)
	check(not machine(drum).moving and machine(drum).energy==1 and machine(feeder).escrow_drive==1,"blocked drum keeps drive; clear feeder pays its own firing")
	wall.free()
	for frame in 2: await get_tree().physics_frame
	await aim_at(feeder); feeder._physics_process(8)
	check(machine(feeder).output.get("rustclay_brick",0)==4,"independent branch makes four actual bricks")
	if not await prepare_firing(feeder): return _finish_lf()
	await aim_at(green); player.interact(); await snap("green-ports")
	await aim_at(lever); player.interact(); await press("Strike the lever")
	blue._physics_process(.5)
	check(manager.write(GREEN_PENDING,player),"save one pending request before both paid receiver operations")
	blue._physics_process(2.5)
	check(machine(drum).moving and machine(drum).energy==0 and machine(feeder).escrow_drive==1 and machine(feeder).energy==0,"one request operates two independently paid receivers")
	check(machine(feeder).escrow_inputs=={"raw_clay":8} and machine(feeder).escrow_fuel=={"wood":1},"second receiver owns exact recipe clay and ordinary heat")
	await workshop_picture("green-workshop")
	await aim_at(feeder); feeder._physics_process(8); drum._physics_process(20)
	check(machine(feeder).output.get("rustclay_brick",0)==8,"two paid firings make eight existing bricks")
	await aim_at(landing); player.interact(); await press("Collect wood")
	check(machine(drum).cargo.is_empty(),"branched paid cargo delivered once")
	check(manager.write(GREEN_COMPLETE,player),"save useful paid Green workshop for Red buffer slice")
	_finish_lf()

func prepare_firing(feeder: ContraptionSite) -> bool:
	if not await gather("raw_clay",8): return false
	await aim_at(feeder); player.interact()
	await press("Load / return supplies")
	await press("Load 8 "+Hud.pretty("raw_clay"))
	if int(machine(feeder).input.get("wood",0))==0:
		await press("Load 4 "+Hud.pretty("wood"))
	await press("Back"); await press("Drive / connections"); await press("Wind by hand")
	player.work_panel.close_panel()
	return check(machine(feeder).energy==1 and machine(feeder).input.get("raw_clay",0)==8,"ordinary hopper and independent hand winding are ready")

func restore_green() -> void:
	var manager := SaveManager.new()
	var saved: Dictionary = JSON.parse_string(FileAccess.get_file_as_string(GREEN_PENDING))
	if not check(manager.read(GREEN_PENDING,player),"fresh process restores Green request: "+manager.last_error): return
	freeze_fixtures()
	check(_sim().leyline_save()==saved.leylines and _sim().contraption_save()==saved.contraptions,"fresh process exact sources, two ports, Blue delay and receiver contents")
	check(JSON.parse_string(_sim().export_json())==JSON.parse_string(saved.sim),"fresh process exact paid inventory")
	var green := fixture("green_junction")
	var blue := fixture("blue_delay")
	var drum := fixture("cargo_winch")
	var feeder := fixture("pressure_feeder")
	var trips := int(machine(drum).completed_trips)
	var cycles := int(machine(feeder).completed_cycles)
	await aim_at(green)
	blue._physics_process(2.5)
	check(machine(drum).moving and machine(feeder).escrow_drive==1,"restored delayed request reaches both receivers once")
	drum._physics_process(20); feeder._physics_process(8)
	blue._physics_process(100)
	check(int(machine(drum).completed_trips)==trips+1 and int(machine(feeder).completed_cycles)==cycles+1,"fresh-process propagation cannot duplicate either execution")
	await aim_at(fixture("winch_landing")); player.interact(); await press("Collect wood")
	check(machine(drum).cargo.is_empty(),"fresh-process actual cargo collected")
