extends "res://tests/living_frontier_green_flow.gd"
const HEAT_ACTIVE := "user://lf2-heat-active.json"
const HEAT_COMPLETE := "user://lf2-heat-complete.json"

func _run_lf() -> void:
	var manager := SaveManager.new()
	if "--heat-restore" in OS.get_cmdline_user_args():
		await restore_heat()
		return _finish_lf()
	var previous: Dictionary = JSON.parse_string(FileAccess.get_file_as_string(GREEN_PENDING))
	if not check(manager.read(GREEN_PENDING,player),"published Green pending checkpoint migrates: "+manager.last_error): return _finish_lf()
	var current: Dictionary = JSON.parse_string(_sim().contraption_save())
	for old: Dictionary in JSON.parse_string(previous.contraptions).machines:
		for now: Dictionary in current.machines:
			if old.key==now.key:
				for field: String in old: check(old[field]==now[field],"Green machine field retained: "+old.key+" / "+field)
	check(_sim().leyline_save()==previous.leylines,"thermal migration leaves every source exact")
	if not check(manager.read(GREEN_COMPLETE,player),"continue paid Green completion: "+manager.last_error): return _finish_lf()
	freeze_fixtures(); refresh_stations()
	if not await gather("iron_ore",4) or not await gather("wood",12): return _finish_lf()
	await aim_at(forge)
	if not craft("smelt_iron",2,forge): return _finish_lf()
	await aim_at(bench)
	var salt := _sim().material_count("red_salt")
	if not craft("assemble_red_heat_buffer",1,bench): return _finish_lf()
	check(_sim().material_count("red_salt")==salt-4,"paid buffer frame uses real Red salt")
	var feeder := fixture("pressure_feeder")
	if not await place_paid_kit("red_heat_buffer_kit",feeder.global_position+Vector3(-2,0,2)): return _finish_lf()
	freeze_fixtures()
	var buffer := fixture("red_heat_buffer")
	print("LF2_PLACED red_heat_buffer ",buffer.global_position)
	await connect_control(buffer,feeder,"Choose heat receiver")
	check(machine(feeder).heat_key==buffer.machine_key,"feeder records unique thermal owner")
	if not await prepare_firing(feeder): return _finish_lf()
	var ledger := _sim().contraption_save()
	check(not feeder.perform("start").ok and _sim().contraption_save()==ledger,"empty heat refuses while preserving all ordinary fuel and drive")
	await aim_at(buffer); player.interact()
	for charge in 4: await press("Pay for 1 heat")
	check(machine(buffer).heat==4 and _sim().material_count("red_salt")==salt-12,"four heat units cost eight additional acquired salt")
	ledger = _sim().contraption_save()
	var pack := _sim().inventory()
	check(not buffer.perform("heat").ok and _sim().contraption_save()==ledger and _sim().inventory()==pack,"full store refuses without taking salt")
	await snap("red-heat-store")
	await aim_at(feeder); player.interact(); await press("Start up to 4 firings")
	feeder._physics_process(2.25)
	check(machine(feeder).escrow_heat==1 and machine(feeder).escrow_fuel.is_empty() and machine(buffer).heat==3,"firing reserves separate heat, clay, drive and output space")
	ledger = _sim().contraption_save()
	check(not buffer.perform("heat").ok and not _sim().contraption_link(buffer.machine_key,"",true).ok and not _sim().contraption_remove(buffer.machine_key).ok and _sim().contraption_save()==ledger,"active return slot, disconnection and dismantling protect exact thermal ownership")
	var wall := StaticBody3D.new()
	var collider := CollisionShape3D.new(); var shape := BoxShape3D.new()
	shape.size=Vector3(.35,1.5,.35); collider.shape=shape; wall.add_child(collider); add_child(wall)
	wall.global_position=buffer.global_position.lerp(feeder.global_position,.5)+Vector3.UP*.85
	for frame in 2: await get_tree().physics_frame
	check(not feeder.feeder_status().ready,"real obstruction blocks the separate heat connection")
	feeder._physics_process(50)
	check(_sim().contraption_save()==ledger,"blocked thermal work preserves exact fraction and payments")
	wall.free()
	for frame in 2: await get_tree().physics_frame
	await aim_at(feeder); player.interact(); await press("Pause")
	check(manager.write(HEAT_ACTIVE,player),"save paused fractional firing and stored thermal contents")
	await snap("red-heat-firing")
	await press("Workshop details"); await press("Cancel requested firings")
	check(machine(buffer).heat==4 and machine(feeder).energy==1 and machine(feeder).input.get("raw_clay",0)==8,"cancel returns reserved heat clay and drive exactly once")
	ledger=_sim().contraption_save()
	check(not feeder.perform("cancel").ok and _sim().contraption_save()==ledger,"second cancel cannot duplicate heat")
	await aim_at(feeder); player.interact(); await press("Start up to 4 firings")
	feeder._physics_process(8)
	check(machine(feeder).output.get("rustclay_brick",0)==12 and machine(buffer).heat==3 and machine(feeder).energy==0,"paid thermal firing adds four real bricks and spends no extra mechanical work")
	check(manager.write(HEAT_COMPLETE,player),"retain paid combined workshop for Catalyst slice")
	# A destructive branch verifies normal removal; D resumes the real saved workshop.
	await aim_at(buffer); player.interact(); await press("Dismantle and recover")
	check(fixture("red_heat_buffer")==null and machine(feeder).heat_key.is_empty(),"idle buffer dismantling clears thermal attachment")
	check(_sim().material_count("red_salt")==salt-10,"only the ordinary two-salt frame refund returns; three stored heat vent")
	_finish_lf()

func restore_heat() -> void:
	var manager := SaveManager.new()
	var previous: Dictionary = JSON.parse_string(FileAccess.get_file_as_string(HEAT_ACTIVE))
	if not check(manager.read(HEAT_ACTIVE,player),"fresh process loads thermal checkpoint: "+manager.last_error): return
	freeze_fixtures()
	check(_sim().contraption_save()==previous.contraptions and _sim().leyline_save()==previous.leylines,"fresh process exact heat owners, fraction, sources and machine ledgers")
	check(JSON.parse_string(_sim().export_json())==JSON.parse_string(previous.sim),"fresh process exact paid material inventory")
	var buffer := fixture("red_heat_buffer")
	var feeder := fixture("pressure_feeder")
	await aim_at(feeder)
	feeder._physics_process(100)
	check(_sim().contraption_save()==previous.contraptions,"saved pause provides no elapsed-time credit")
	player.interact(); await press("Resume")
	feeder._physics_process(5.75)
	check(machine(buffer).heat==3 and machine(feeder).output.get("rustclay_brick",0)==12,"saved thermal firing completes once using its held heat")
	var complete := _sim().contraption_save()
	feeder._physics_process(100)
	check(_sim().contraption_save()==complete,"no unaffordable continuation or restart replay")
	# Restart the earlier branch to verify dismantling an active feeder returns
	# its held heat to the still-present owner, not to the player's inventory.
	check(manager.read(HEAT_ACTIVE,player),"restore independent dismantling branch")
	freeze_fixtures(); buffer=fixture("red_heat_buffer"); feeder=fixture("pressure_feeder")
	var before := _sim().inventory()
	await aim_at(feeder); player.interact(); await press("Workshop details"); await press("Dismantle and recover")
	check(fixture("pressure_feeder")==null and machine(buffer).heat==4 and machine(buffer).link.is_empty(),"active feeder removal returns one reserved heat and unlinks")
	check(_sim().material_count("raw_clay")==int(before.get("raw_clay",0))+8 and _sim().material_count("rustclay_brick")==int(before.get("rustclay_brick",0))+8,"active feeder removal recovers exact held clay and completed tray")
